### ISSUE TITLE
Open aea init appends unwanted string on ipfs-node

### ISSUE THREAD

**Issue by jmoreira-valory** [valory-xyz/open-aea#719]
**Describe the bug**

On Windows system, the command

```
autonomy init --reset --author valory --remote --ipfs --ipfs-node "/dns/registry.autonolas.tech/tcp/443/https"
```

produces

```
cat ~/.aea/cli_config.yaml
author: valory
registry_config:
  default: remote
  settings:
    local:
      default_packages_path: null
    remote:
      default: ipfs
      http:
        auth_token: null
        registry_api_url: null
      ipfs:
        ipfs_node: C:/Program Files/Git/dns/registry.autonolas.tech/tcp/443/https
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
i am on OS Window 10 Pro
Python version 3.10
Poetry 1.7.1
Docker version 4.26.1
running on Git bash

**Additional context**
Appeared to a Discord participant.
